import test from 'node:test';
import assert from 'node:assert/strict';
import { validateConfig, validateReport } from '../src/validate.js';

const valid = {
  schemaVersion: 1,
  project: 'demo',
  prompts: [{ id: 'steps', label: 'Steps' }],
  commands: [{ name: 'Node', command: 'node', args: ['--version'], timeoutMs: 1000 }]
};

test('accepts a safe configuration', () => assert.equal(validateConfig(valid).ok, true));

test('blocks shell interpreters', () => {
  const config = structuredClone(valid);
  config.commands[0] = { name: 'unsafe', command: 'bash', args: ['-c', 'echo hi'] };
  assert.equal(validateConfig(config).ok, false);
});

test('rejects duplicate prompt identifiers', () => {
  const config = structuredClone(valid);
  config.prompts.push({ id: 'steps', label: 'Again' });
  assert.match(validateConfig(config).errors.join(' '), /duplicate/);
});

test('detects secrets left in a report', () => {
  const report = '<!-- Generated by TriagePack -->\n## Diagnostics\ntoken=ghp_abcdefghijklmnopqrstuvwxyz1234567890';
  assert.equal(validateReport(report).ok, false);
});
