import { readFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import os from 'node:os';
import { redact, redactObject } from './redact.js';

const BLOCKED_EXECUTABLES = new Set([
  'sh', 'bash', 'zsh', 'fish', 'cmd', 'cmd.exe', 'powershell', 'powershell.exe',
  'pwsh', 'pwsh.exe', 'cscript', 'wscript', 'mshta'
]);

export async function loadConfig(path) {
  try {
    return JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    if (error.code === 'ENOENT') throw new Error(`config not found: ${path}; run "triagepack init" first`);
    if (error instanceof SyntaxError) throw new Error(`invalid JSON in ${path}: ${error.message}`);
    throw error;
  }
}

function runCommand(item, cwd) {
  const executable = item.command.toLowerCase().split(/[\\/]/).pop();
  if (BLOCKED_EXECUTABLES.has(executable)) {
    return Promise.resolve({ name: item.name, command: [item.command, ...item.args], status: 'blocked', output: 'Shell interpreters are not allowed.' });
  }
  return new Promise((resolveResult) => {
    const inheritedEnvironment = Object.fromEntries(Object.entries({
      PATH: process.env.PATH,
      Path: process.env.Path,
      PATHEXT: process.env.PATHEXT,
      SYSTEMROOT: process.env.SYSTEMROOT,
      WINDIR: process.env.WINDIR,
      HOME: process.env.HOME,
      USERPROFILE: process.env.USERPROFILE,
      TMPDIR: process.env.TMPDIR,
      TMP: process.env.TMP,
      TEMP: process.env.TEMP,
      LANG: process.env.LANG,
      LC_ALL: process.env.LC_ALL
    }).filter(([, value]) => value !== undefined));
    const child = spawn(item.command, item.args, {
      cwd,
      shell: false,
      windowsHide: true,
      env: {
        ...inheritedEnvironment,
        NO_COLOR: '1',
        CI: '1'
      },
      stdio: ['ignore', 'pipe', 'pipe']
    });
    const chunks = [];
    let size = 0;
    let truncated = false;
    const limit = item.maxOutputBytes || 20_000;
    const capture = (chunk) => {
      if (size >= limit) return void (truncated = true);
      const slice = chunk.subarray(0, Math.max(0, limit - size));
      chunks.push(slice);
      size += slice.length;
      if (slice.length < chunk.length) truncated = true;
    };
    child.stdout.on('data', capture);
    child.stderr.on('data', capture);
    const timer = setTimeout(() => child.kill(), item.timeoutMs || 10_000);
    child.on('error', (error) => {
      clearTimeout(timer);
      resolveResult({ name: item.name, command: [item.command, ...item.args], status: 'error', output: error.message });
    });
    child.on('close', (code, signal) => {
      clearTimeout(timer);
      const suffix = truncated ? '\n[output truncated]' : '';
      resolveResult({
        name: item.name,
        command: [item.command, ...item.args],
        status: signal ? 'timeout' : code === 0 ? 'ok' : `exit ${code}`,
        output: `${Buffer.concat(chunks).toString('utf8').trim()}${suffix}`
      });
    });
  });
}

export async function collectReport(config, options = {}) {
  const cwd = options.cwd || process.cwd();
  const results = [];
  for (const command of config.commands) results.push(await runCommand(command, cwd));
  return redactObject({
    format: 'triagepack/v1',
    project: config.project,
    issueUrl: config.issueUrl || null,
    generatedAt: new Date().toISOString(),
    answers: options.answers || {},
    system: {
      platform: process.platform,
      architecture: process.arch,
      osRelease: os.release(),
      node: process.version
    },
    diagnostics: results
  });
}

function fence(value) {
  return String(value || '(no output)').replace(/```/g, '``\u200b`');
}

export function renderReport(report) {
  const answers = Object.entries(report.answers)
    .map(([key, value]) => `### ${key}\n\n${redact(value) || '_Not provided_'}\n`)
    .join('\n');
  const diagnostics = report.diagnostics.map((item) =>
    `### ${item.name}\n\n- Status: \`${item.status}\`\n- Command: \`${item.command.map(redact).join(' ')}\`\n\n\`\`\`text\n${fence(item.output)}\n\`\`\`\n`
  ).join('\n');
  return `<!-- Generated by TriagePack. Review before posting publicly. -->
# ${report.project} diagnostic report

> TriagePack automatically redacted common secrets and local user paths. Please still review this report before sharing it.

## Report details

- Format: \`${report.format}\`
- Generated: ${report.generatedAt}
- Platform: ${report.system.platform} / ${report.system.architecture}
- OS release: ${report.system.osRelease}
- Node.js: ${report.system.node}

## Reproduction

${answers || '_No interactive answers were provided._\n'}
## Diagnostics

${diagnostics}
---
Generated locally by TriagePack. No data was uploaded.
`;
}
