import { looksSensitive } from './redact.js';

const blocked = /^(?:sh|bash|zsh|fish|cmd(?:\.exe)?|powershell(?:\.exe)?|pwsh(?:\.exe)?|cscript|wscript|mshta)$/i;

export function validateConfig(config) {
  const errors = [];
  if (!config || typeof config !== 'object') return { ok: false, errors: ['config must be an object'] };
  if (config.schemaVersion !== 1) errors.push('schemaVersion must be 1');
  if (typeof config.project !== 'string' || !config.project.trim()) errors.push('project is required');
  if (!Array.isArray(config.prompts)) errors.push('prompts must be an array');
  if (!Array.isArray(config.commands)) errors.push('commands must be an array');
  for (const [index, item] of (config.commands || []).entries()) {
    if (!item.name || !item.command) errors.push(`commands[${index}] requires name and command`);
    if (!Array.isArray(item.args) || item.args.some((arg) => typeof arg !== 'string')) errors.push(`commands[${index}].args must be a string array`);
    if (blocked.test(String(item.command).split(/[\\/]/).pop())) errors.push(`commands[${index}] uses a blocked shell interpreter`);
    if (item.timeoutMs && (item.timeoutMs < 100 || item.timeoutMs > 60_000)) errors.push(`commands[${index}].timeoutMs must be 100..60000`);
  }
  const ids = new Set();
  for (const [index, prompt] of (config.prompts || []).entries()) {
    if (!prompt.id || !prompt.label) errors.push(`prompts[${index}] requires id and label`);
    if (ids.has(prompt.id)) errors.push(`duplicate prompt id: ${prompt.id}`);
    ids.add(prompt.id);
  }
  return { ok: errors.length === 0, errors };
}

export function validateReport(report) {
  const errors = [];
  if (!report.includes('Generated by TriagePack')) errors.push('missing TriagePack report marker');
  if (looksSensitive(report)) errors.push('report still appears to contain a secret');
  if (!report.includes('## Diagnostics')) errors.push('missing diagnostics section');
  return { ok: errors.length === 0, errors };
}
